Repository jenkins-x-plugins/jx-pipeline, pull requests merged in 2020-12, with the labels that each got.

#132 refactor: remove old v2 requirements
  go.mod
  go.sum
  pkg/cmd/activities/activities.go
  pkg/cmd/activities/activities_test.go
  pkg/cmd/getlog/logs.go
  pkg/cmd/pod/pod.go
  pkg/cmd/start/start.go
  pkg/cmd/start/start_test.go
  pkg/cmd/stop/stop.go
  pkg/cmd/wait/wait.go
  pkg/pipelines/pipelines.go
  pkg/pipelines/pipelines_test.go
  pkg/pipelines/test_data/merge/expected.yaml
  pkg/pipelines/test_data/merge/pa.yaml
  pkg/plugins/helpers.go
  pkg/sourcerepos/sourcerepositories.go
  pkg/sourcerepos/sourcerepositories_test.go
  pkg/tektonlog/constants.go
  pkg/tektonlog/filter.go
  pkg/tektonlog/tektonlog.go
  pkg/tektonlog/test_data/multiple_stages_failure_activity_done_run_not_done/activity.yml
  pkg/tektonlog/test_data/multiple_stages_with_failure_in_first_stage/activity.yml
  pkg/testpipelines/pipelines.go
Labels: approved, size/L

#136 fix: avoid nil pointer
  go.sum
  pkg/lighthouses/scm_provider.go
Labels: approved, size/XS

#137 refactor: move traditional CRDs back to jenkins.io group so we dont need to create new CRDs
  go.mod
  go.sum
  pkg/cmd/activities/activities.go
  pkg/cmd/start/start_test.go
  pkg/cmd/wait/wait.go
  pkg/pipelines/pipelines.go
  pkg/pipelines/pipelines_test.go
  pkg/plugins/helpers.go
  pkg/sourcerepos/sourcerepositories.go
  pkg/sourcerepos/sourcerepositories_test.go
  pkg/tektonlog/constants.go
  pkg/tektonlog/filter.go
  pkg/tektonlog/tektonlog.go
  pkg/testpipelines/pipelines.go
Labels: approved, size/XXL

#140 chore: upgrade pipelines
  .lighthouse/jenkins-x/Kptfile
  .lighthouse/jenkins-x/pullrequest.yaml
  .lighthouse/jenkins-x/release.yaml
  .lighthouse/jenkins-x/triggers.yaml
Labels: size/XL, updatebot

#162 fix: add updatebot configuration
  .jx/updatebot.yaml
Labels: approved, size/S

#173 fix: handle starting presubmit or post submits
  docs/cmd/jx-pipeline.md
  docs/cmd/jx-pipeline_activities.md
  docs/cmd/jx-pipeline_fmt.md
  docs/cmd/jx-pipeline_get.md
  docs/cmd/jx-pipeline_import.md
  docs/cmd/jx-pipeline_lint.md
  docs/cmd/jx-pipeline_log.md
  docs/cmd/jx-pipeline_pods.md
  docs/cmd/jx-pipeline_start.md
  docs/cmd/jx-pipeline_stop.md
  docs/cmd/jx-pipeline_version.md
  docs/cmd/jx-pipeline_wait.md
  docs/man/man1/jx-pipeline-lint.1
  docs/man/man1/jx-pipeline-start.1
  docs/man/man1/jx-pipeline-wait.1
  go.mod
  go.sum
  pkg/cmd/start/start.go
  pkg/cmd/start/start_test.go
Labels: approved, size/XXL
