Repository jenkins-x-plugins/jx-pipeline, pull requests merged in 2020-11, with the labels that each got.

#92 fix: add fmt and lint commands
  docs/cmd/jx-pipeline.md
  docs/cmd/jx-pipeline_activities.md
  docs/cmd/jx-pipeline_get.md
  docs/cmd/jx-pipeline_import.md
  docs/cmd/jx-pipeline_log.md
  docs/cmd/jx-pipeline_pods.md
  docs/cmd/jx-pipeline_start.md
  docs/cmd/jx-pipeline_stop.md
  docs/cmd/jx-pipeline_version.md
  docs/cmd/jx-pipeline_wait.md
  docs/man/man1/jx-pipeline.1
  go.mod
  go.sum
  pkg/cmd/fmt/default_parameters.go
  pkg/cmd/fmt/fmt.go
  pkg/cmd/lint/lint.go
  pkg/cmd/root.go
  pkg/lighthouses/scm_provider.go
Labels: approved, size/XL

#93 fix: polish linter
  go.sum
  pkg/cmd/lint/lint.go
Labels: approved, size/S

#100 fix: improve output when importing
  go.mod
  go.sum
  pkg/cmd/fmt/fmt.go
  pkg/cmd/wait/wait.go
Labels: approved, size/M

#101 chore: upgrade docs and fix typo
  docs/cmd/jx-pipeline.md
  docs/cmd/jx-pipeline_activities.md
  docs/cmd/jx-pipeline_fmt.md
  docs/cmd/jx-pipeline_get.md
  docs/cmd/jx-pipeline_import.md
  docs/cmd/jx-pipeline_lint.md
  docs/cmd/jx-pipeline_log.md
  docs/cmd/jx-pipeline_pods.md
  docs/cmd/jx-pipeline_start.md
  docs/cmd/jx-pipeline_stop.md
  docs/cmd/jx-pipeline_version.md
  docs/cmd/jx-pipeline_wait.md
  docs/man/man1/jx-pipeline-fmt.1
  docs/man/man1/jx-pipeline-lint.1
  go.mod
  pkg/cmd/wait/wait.go
Labels: approved, size/L

#104 fix: add unit test for lint
  go.mod
  go.sum
  pkg/cmd/lint/lint.go
  pkg/cmd/lint/lint_test.go
  pkg/cmd/lint/test_data/.lighthouse/jenkins-x/demo-deploy-kubectl.yaml
  pkg/cmd/lint/test_data/.lighthouse/jenkins-x/git-clone.yaml
  pkg/cmd/lint/test_data/.lighthouse/jenkins-x/kaniko.yaml
  pkg/cmd/lint/test_data/.lighthouse/jenkins-x/release.yaml
  pkg/cmd/lint/test_data/.lighthouse/jenkins-x/triggers.yaml
  pkg/cmd/lint/test_data/.lighthouse/jenkins-x/unit-tests.yaml
Labels: approved, size/L

#112 chore: fix typo
  pkg/cmd/wait/wait.go
Labels: approved, lgtm, ok-to-test, size/XS

#111 fix: better linting
  go.mod
  go.sum
  pkg/cmd/get/get.go
  pkg/cmd/lint/lint.go
  pkg/cmd/lint/test_data/.lighthouse/jenkins-x/demo-deploy-kubectl.yaml
  pkg/cmd/lint/test_data/.lighthouse/jenkins-x/git-clone.yaml
  pkg/cmd/lint/test_data/.lighthouse/jenkins-x/kaniko.yaml
  pkg/cmd/lint/test_data/.lighthouse/jenkins-x/release.yaml
  pkg/cmd/lint/test_data/.lighthouse/jenkins-x/unit-tests.yaml
  pkg/plugins/helpers.go
  pkg/plugins/helpers_test.go
  pkg/plugins/versions.go
Labels: approved, size/L

#120 fix: handle ctrl-c
  go.mod
  go.sum
  pkg/cmd/activities/activities.go
  pkg/cmd/activities/activities_test.go
  pkg/cmd/get/get.go
  pkg/cmd/get/get_test.go
  pkg/cmd/getlog/logs.go
  pkg/cmd/lint/lint.go
  pkg/cmd/pod/pod.go
  pkg/cmd/start/start.go
  pkg/cmd/start/start_test.go
  pkg/cmd/stop/stop.go
  pkg/cmd/wait/wait.go
  pkg/lighthouses/scm_provider.go
  pkg/sourcerepos/sourcerepositories.go
  pkg/sourcerepos/sourcerepositories_test.go
  pkg/tektonlog/pipelines.go
  pkg/tektonlog/tektonlog.go
  pkg/testpipelines/pipelines.go
  pkg/triggers/triggers.go
Labels: approved, size/L

#125 fix: support recursive linting
  go.mod
  go.sum
  pkg/cmd/lint/lint.go
Labels: approved, size/L
