Repository jenkins-x-plugins/jx-pipeline, pull requests merged in 2021-03, with the labels that each got.

#312 fix: detect Jenkins env vars
  go.mod
  go.sum
  pkg/cmd/effective/effective.go
Labels: approved, size/M

#342 fix: upgrade deps
  go.mod
  go.sum
  pkg/cmd/override/test_data/expected.yaml
Labels: approved, size/M

#354 fix: override steps in composite tasks
  cmd/effective/main.go
  docs/cmd/jx-pipeline.md
  docs/cmd/jx-pipeline_activities.md
  docs/cmd/jx-pipeline_convert.md
  docs/cmd/jx-pipeline_effective.md
  docs/cmd/jx-pipeline_fmt.md
  docs/cmd/jx-pipeline_get.md
  docs/cmd/jx-pipeline_import.md
  docs/cmd/jx-pipeline_lint.md
  docs/cmd/jx-pipeline_log.md
  docs/cmd/jx-pipeline_override.md
  docs/cmd/jx-pipeline_pods.md
  docs/cmd/jx-pipeline_start.md
  docs/cmd/jx-pipeline_stop.md
  docs/cmd/jx-pipeline_version.md
  docs/cmd/jx-pipeline_wait.md
  docs/man/man1/jx-pipeline-effective.1
  docs/man/man1/jx-pipeline-override.1
  go.mod
  go.sum
  pkg/cmd/convert/convert_test.go
  pkg/cmd/effective/effective.go
  pkg/cmd/override/override.go
  pkg/cmd/override/override_test.go
  pkg/cmd/override/test_data/fake_file_browser/tasks/javascript/release.yaml
  pkg/cmd/override/test_data/jenkins-x/jx3-pipeline-catalog/refs/myversionstreamref/tasks/javascript/release.yaml
  pkg/cmd/override/test_data/step/.lighthouse/jenkins-x/pullrequest.yaml
  pkg/cmd/override/test_data/step/.lighthouse/jenkins-x/release.yaml
  pkg/cmd/override/test_data/step/.lighthouse/jenkins-x/triggers.yaml
  pkg/cmd/override/test_data/step/expected.yaml
  pkg/cmd/override/test_data/task/expected.yaml
  pkg/cmd/override/test_data/task/pipeline.yaml
  pkg/cmd/stop/stop.go
  pkg/lighthouses/catalogs.go
  pkg/lighthouses/resolvers.go
  pkg/pipelines/processor/inliner.go
Labels: approved, size/XL

#355 chore: fix lets not fail if batch mode
  pkg/cmd/getlog/logs.go
Labels: approved, size/XS

#356 fix: upgrade dependencies
  go.mod
  go.sum
Labels: approved, size/XS

#357 fix: specify the parameter defaults on the PipelineRun spec
  pkg/cmd/effective/effective.go
Labels: approved, size/S

#364 fix: discover the git URL from the current dir
  .jx/updatebot.yaml
  go.mod
  go.sum
  hack/changelog-header.md
  pkg/cmd/effective/effective.go
  pkg/lighthouses/resolvers.go
Labels: approved, size/M

#367 chore: move to plugins org
  .goreleaser.yml
  Makefile
  README.md
  cmd/app/main-win.go
  cmd/app/main.go
  cmd/docs/main.go
  cmd/effective/main.go
  cmd/main.go
  go.mod
  go.sum
  hack/changelog-header.md
  pkg/cloud/buckets/buckets.go
  pkg/cloud/buckets/buckets_test.go
  pkg/cmd/activities/activities_test.go
  pkg/cmd/convert/convert.go
  pkg/cmd/convert/convert_test.go
  pkg/cmd/effective/effective.go
  pkg/cmd/effective/effective_jenkins_integration_test.go
  pkg/cmd/effective/effective_test.go
  pkg/cmd/get/get.go
  pkg/cmd/get/get_test.go
  pkg/cmd/getlog/logs.go
  pkg/cmd/importcmd/import.go
  pkg/cmd/importcmd/import_test.go
  pkg/cmd/lint/lint.go
  pkg/cmd/lint/lint_test.go
  pkg/cmd/override/override.go
  pkg/cmd/override/override_test.go
  pkg/cmd/pod/pod.go
  pkg/cmd/root.go
  pkg/cmd/start/start.go
  pkg/cmd/start/start_test.go
  pkg/cmd/stop/stop.go
  pkg/cmd/wait/wait.go
  pkg/pipelines/pipelines_test.go
  pkg/pipelines/processor/inliner.go
  pkg/pipelines/processor/uses_migrator_test.go
  pkg/plugins/helpers_test.go
  pkg/sourcerepos/sourcerepositories_test.go
  pkg/tektonlog/pipelines_test.go
  pkg/tektonlog/tektonlog.go
Labels: approved, size/L
