Repository jenkins-x-plugins/jx-pipeline, pull requests merged in 2021-01, with the labels that each got.

#201 chore: upgrade deps
  go.mod
  go.sum
Labels: approved, lgtm, ok-to-test, size/L

#217 chore: dep bump
  go.mod
  go.sum
Labels: approved, lgtm, ok-to-test, size/M

#224 fix: use the right stage name in the logs
  pkg/tektonlog/tektonlog.go
Labels: approved, lgtm, ok-to-test, size/XS

#230 chore: upgrade go dependencies
  go.mod
  go.sum
Labels: size/S, updatebot

#232 chore: upgrade go dependencies
  go.mod
  go.sum
Labels: size/XS, updatebot

#233 chore: upgrade go dependencies
  go.mod
  go.sum
Labels: updatebot

#240 chore: upgrade dependencies
  go.mod
  go.sum
  pkg/cmd/fmt/fmt.go
  pkg/cmd/importcmd/import.go
  pkg/cmd/lint/lint.go
  pkg/cmd/start/start.go
  pkg/cmd/start/start_test.go
  pkg/cmd/stop/stop.go
  pkg/cmd/wait/wait.go
  pkg/lighthouses/clients.go
  pkg/lighthouses/scm_provider.go
  pkg/triggers/triggers.go
Labels: approved, size/XL

#245 fix: bug in missing labels for get/stop pipeline
  go.mod
  go.sum
  pkg/cmd/get/get.go
  pkg/cmd/stop/stop.go
  pkg/pipelines/pipelines.go
Labels: approved, size/M

#251 fix: support converting repository pipelines
  docs/cmd/jx-pipeline.md
  docs/cmd/jx-pipeline_activities.md
  docs/cmd/jx-pipeline_convert.md
  docs/cmd/jx-pipeline_effective.md
  docs/cmd/jx-pipeline_fmt.md
  docs/cmd/jx-pipeline_get.md
  docs/cmd/jx-pipeline_import.md
  docs/cmd/jx-pipeline_lint.md
  docs/cmd/jx-pipeline_log.md
  docs/cmd/jx-pipeline_pods.md
  docs/cmd/jx-pipeline_start.md
  docs/cmd/jx-pipeline_stop.md
  docs/cmd/jx-pipeline_version.md
  docs/cmd/jx-pipeline_wait.md
  docs/man/man1/jx-pipeline-convert.1
  go.mod
  go.sum
  pkg/cmd/convert/convert.go
  pkg/cmd/convert/convert_test.go
  pkg/cmd/convert/test_data/catalog/expected/packs/javascript/.lighthouse/jenkins-x/pullrequest.yaml
  pkg/cmd/convert/test_data/catalog/expected/packs/javascript/.lighthouse/jenkins-x/release.yaml
  pkg/cmd/convert/test_data/catalog/expected/packs/javascript/.lighthouse/jenkins-x/triggers.yaml
  pkg/cmd/convert/test_data/catalog/expected/packs/javascript/Dockerfile
  pkg/cmd/convert/test_data/catalog/expected/tasks/javascript/pullrequest.yaml
  pkg/cmd/convert/test_data/catalog/expected/tasks/javascript/release.yaml
  pkg/cmd/convert/test_data/catalog/pipeline-catalog/packs/javascript/.lighthouse/jenkins-x/pullrequest.yaml
  pkg/cmd/convert/test_data/catalog/pipeline-catalog/packs/javascript/.lighthouse/jenkins-x/release.yaml
  pkg/cmd/convert/test_data/catalog/pipeline-catalog/packs/javascript/.lighthouse/jenkins-x/triggers.yaml
  pkg/cmd/convert/test_data/catalog/pipeline-catalog/packs/javascript/Dockerfile
  pkg/cmd/convert/test_data/jenkins-x/jx3-pipeline-catalog/refs/myversionstreamref/packs/go-plugin/.lighthouse/jenkins-x/pullrequest.yaml
  pkg/cmd/convert/test_data/jenkins-x/jx3-pipeline-catalog/refs/myversionstreamref/packs/go-plugin/.lighthouse/jenkins-x/release.yaml
  pkg/cmd/convert/test_data/jenkins-x/jx3-pipeline-catalog/refs/myversionstreamref/packs/go-plugin/.lighthouse/jenkins-x/triggers.yaml
  pkg/cmd/convert/test_data/repo/expected/.lighthouse/jenkins-x/pullrequest.yaml
  pkg/cmd/convert/test_data/repo/expected/.lighthouse/jenkins-x/release.yaml
  pkg/cmd/convert/test_data/repo/expected/.lighthouse/jenkins-x/triggers.yaml
  pkg/cmd/convert/test_data/repo/jx-cli/.lighthouse/jenkins-x/Kptfile
  pkg/cmd/convert/test_data/repo/jx-cli/.lighthouse/jenkins-x/pullrequest.yaml
  pkg/cmd/convert/test_data/repo/jx-cli/.lighthouse/jenkins-x/release.yaml
  pkg/cmd/convert/test_data/repo/jx-cli/.lighthouse/jenkins-x/triggers.yaml
  pkg/lighthouses/resolvers.go
  pkg/pipelines/processor/helpers.go
  pkg/pipelines/processor/uses_migrator.go
Labels: approved, size/XXL

#258 fix: handle migration of prepend/append annotations
  go.mod
  go.sum
  pkg/cmd/convert/convert.go
  pkg/cmd/convert/test_data/catalog/expected/packs/javascript/.lighthouse/jenkins-x/pullrequest.yaml
  pkg/cmd/convert/test_data/catalog/expected/packs/javascript/.lighthouse/jenkins-x/release.yaml
  pkg/cmd/importcmd/import.go
  pkg/cmd/start/start.go
  pkg/lighthouses/resolvers.go
  pkg/pipelines/processor/uses_migrator.go
Labels: approved, size/M

#259 fix: default to removing Kptfile in git
  pkg/cmd/convert/convert.go
  pkg/cmd/convert/convert_test.go
Labels: approved, size/M

#260 chore: upgrade pipelines
  .lighthouse/jenkins-x/Kptfile
  .lighthouse/jenkins-x/pullrequest.yaml
  .lighthouse/jenkins-x/release.yaml
Labels: size/L, updatebot

#267 fix: open effective pipeline in editor
  docs/cmd/jx-pipeline.md
  docs/cmd/jx-pipeline_activities.md
  docs/cmd/jx-pipeline_convert.md
  docs/cmd/jx-pipeline_effective.md
  docs/cmd/jx-pipeline_fmt.md
  docs/cmd/jx-pipeline_get.md
  docs/cmd/jx-pipeline_import.md
  docs/cmd/jx-pipeline_lint.md
  docs/cmd/jx-pipeline_log.md
  docs/cmd/jx-pipeline_pods.md
  docs/cmd/jx-pipeline_start.md
  docs/cmd/jx-pipeline_stop.md
  docs/cmd/jx-pipeline_version.md
  docs/cmd/jx-pipeline_wait.md
  docs/man/man1/jx-pipeline-effective.1
  go.mod
  go.sum
  pkg/cmd/effective/effective.go
Labels: approved, size/L

#265 fix: bucket URL split for min.io
  pkg/cloud/buckets/buckets.go
Labels: approved, lgtm, ok-to-test, size/XS

#269 chore: gen docs
  docs/cmd/jx-pipeline_override.md
  docs/man/man1/jx-pipeline-override.1
Labels: size/L

#270 fix: handle converting old jenkins-x.yml files
  go.mod
  go.sum
  pkg/cmd/convert/convert.go
Labels: approved, size/M

#271 chore: fix pipeline
  .lighthouse/jenkins-x/release.yaml
Labels: size/S
