Repository jenkins-x-plugins/jx-pipeline, pull requests merged in 2021-05, with the labels that each got.

#377 chore: ensure opentelemetry annotations are not copied
  pkg/pipelines/pipelines.go
  pkg/pipelines/test_data/create/pipelinerun.yaml
  pkg/pipelines/test_data/initial/pipelinerun.yaml
  pkg/pipelines/test_data/merge/pipelinerun.yaml
Labels: approved, lgtm, ok-to-test, size/S

#287 feat: defer resolving the pipeline until after the name is selected
  pkg/cmd/effective/effective.go
Labels: approved, lgtm, ok-to-test, size/M

#380 fix: add helper command to set properties on pipeline files
  docs/cmd/jx-pipeline.md
  docs/cmd/jx-pipeline_activities.md
  docs/cmd/jx-pipeline_convert.md
  docs/cmd/jx-pipeline_effective.md
  docs/cmd/jx-pipeline_fmt.md
  docs/cmd/jx-pipeline_get.md
  docs/cmd/jx-pipeline_grid.md
  docs/cmd/jx-pipeline_import.md
  docs/cmd/jx-pipeline_lint.md
  docs/cmd/jx-pipeline_log.md
  docs/cmd/jx-pipeline_override.md
  docs/cmd/jx-pipeline_pods.md
  docs/cmd/jx-pipeline_start.md
  docs/cmd/jx-pipeline_stop.md
  docs/cmd/jx-pipeline_version.md
  docs/cmd/jx-pipeline_wait.md
  docs/man/man1/jx-pipeline.1
  go.mod
  go.sum
  pkg/cmd/root.go
  pkg/cmd/set/set.go
  pkg/cmd/set/set_test.go
  pkg/cmd/set/test_data/cheese/expected.yaml
  pkg/cmd/set/test_data/cheese/release.yaml
  pkg/pipelines/processor/helpers.go
  pkg/pipelines/processor/modify.go
Labels: approved, size/XL

#379 fix: fixes `SplitBucketURL` to revert the 'min.io' specific change for broken s3 urls
  pkg/cloud/buckets/buckets.go
  pkg/cloud/buckets/buckets_test.go
Labels: approved, lgtm, ok-to-test, size/S

#381 fix: ensure we don't loop while reading pod logs
  pkg/tektonlog/tektonlog.go
Labels: approved, lgtm, ok-to-test, size/S

#384 fix: tektonlog: be smarter when waiting for pod completion
  pkg/tektonlog/tektonlog.go
Labels: approved, lgtm, ok-to-test, size/S

#385 fix(#382): fix logs pulling for pipelines with multiple stages
  pkg/tektonlog/tektonlog.go
Labels: approved, lgtm, ok-to-test, size/L

#386 chore: refactored code
  go.mod
  go.sum
  pkg/cmd/get/get.go
  pkg/cmd/grid/model.go
  pkg/cmd/stop/stop.go
  pkg/pipelines/pipelines.go
Labels: approved, size/L

#387 fix: add better validation
  docs/cmd/jx-pipeline.md
  docs/cmd/jx-pipeline_activities.md
  docs/cmd/jx-pipeline_convert.md
  docs/cmd/jx-pipeline_effective.md
  docs/cmd/jx-pipeline_fmt.md
  docs/cmd/jx-pipeline_get.md
  docs/cmd/jx-pipeline_grid.md
  docs/cmd/jx-pipeline_import.md
  docs/cmd/jx-pipeline_lint.md
  docs/cmd/jx-pipeline_log.md
  docs/cmd/jx-pipeline_override.md
  docs/cmd/jx-pipeline_pods.md
  docs/cmd/jx-pipeline_start.md
  docs/cmd/jx-pipeline_stop.md
  docs/cmd/jx-pipeline_version.md
  docs/cmd/jx-pipeline_wait.md
  docs/man/man1/jx-pipeline-lint.1
  pkg/cmd/lint/lint.go
  pkg/cmd/lint/lint_test.go
  pkg/cmd/lint/test_data/invalid/missing_volume.yaml
  pkg/cmd/lint/test_data/valid/.lighthouse/jenkins-x/release.yaml
  pkg/cmd/lint/test_data/valid/.lighthouse/jenkins-x/triggers.yaml
Labels: approved, size/L

#388 chore: upgrade deps
  go.mod
  go.sum
Labels: approved, size/M
