Repository jenkins-x-plugins/jx-pipeline, pull requests merged in 2022-09, with the labels that each got.

#490 feat: reference download syft from pipeline catalog
  .lighthouse/jenkins-x/release.yaml
Labels: approved, size/S, ok-to-test

#491 feat: container sbom push
  .lighthouse/jenkins-x/release.yaml
Labels: approved, size/XS, lgtm, ok-to-test

#493 fix: revert the sbom container push
  .lighthouse/jenkins-x/release.yaml
Labels: approved, lgtm, size/S, ok-to-test

#494 feat: add supply chain tasks
  .lighthouse/jenkins-x/release.yaml
Labels: approved, size/S, ok-to-test

#495 fix: create image tar for sbom analysis
  .gitignore
  .lighthouse/jenkins-x/release.yaml
Labels: size/S

#496 fix: add cred helpers and sbom to gitignore
  .gitignore
  .lighthouse/jenkins-x/pullrequest.yaml
  .lighthouse/jenkins-x/release.yaml
  Makefile
Labels: approved, size/S

#497 fix: Using pager for logs
  pkg/cmd/getlog/logs.go
  pkg/cmd/getlog/tekton_logs.go
  pkg/cmd/getlog/tekton_logs_win.go
  pkg/cmd/lint/lint.go
  pkg/lighthouses/pipelines.go
  pkg/pipelines/processor/helpers.go
Labels: approved, size/S

#498 fix: Look for pipeline logs in jx
  pkg/cmd/getlog/logs.go
Labels: approved, size/XS

#502 fix: version command output
  .goreleaser.yml
Labels: approved, size/XS

#500 chore: upgrade tektoncd pipeline module to 0.32.4
  .jx/updatebot.yaml
  Makefile
  go.mod
  go.sum
Labels: approved, size/XL
