Repository jenkins-x-plugins/jx-pipeline, pull requests merged in 2022-07, with the labels that each got.

#482 fix: linting issues
  cmd/docs/main.go
  cmd/docs/md_docs.go
  go.mod
  go.sum
  pkg/cloud/buckets/buckets.go
  pkg/cmd/activities/activities.go
  pkg/cmd/convert/convert.go
  pkg/cmd/effective/effective.go
  pkg/cmd/effective/effective_jenkins_integration_test.go
  pkg/cmd/env/env.go
  pkg/cmd/fmt/fmt.go
  pkg/cmd/get/get.go
  pkg/cmd/grid/grid.go
  pkg/cmd/grid/view.go
  pkg/cmd/importcmd/import.go
  pkg/cmd/lint/lint.go
  pkg/cmd/override/override.go
  pkg/cmd/set/set_test.go
  pkg/lighthouses/pipelines.go
  pkg/pipelines/pipelines.go
  pkg/pipelines/pipelines_test.go
  pkg/pipelines/processor/helpers.go
  pkg/pipelines/processor/inliner.go
  pkg/pipelines/processor/uses_migrator.go
  pkg/tektonlog/tektonlog.go
Labels: size/M, approved, ok-to-test

#484 feat: generate sbom for jx-pipeline binaries
  .goreleaser.yml
Labels: approved, size/XS

#485 fix: default jx-pipeline to use github unless specified otherwise
  .goreleaser.yml
  go.mod
  go.sum
  pkg/lighthouses/resolvers.go
Labels: approved, size/S

#486 feat: add sbom generation to jx-pipeline
  .goreleaser.yml
  .lighthouse/jenkins-x/release.yaml
Labels: approved, size/S

#487 fix: missing executable in goreleaser
  .lighthouse/jenkins-x/release.yaml
Labels: approved, size/XS

#488 fix: add syft and codecov to gitignore
  .gitignore
  .goreleaser.yml
Labels: approved, size/S
