Repository jenkins-x-plugins/jx-pipeline, pull requests merged in 2022-04, with the labels that each got.

#442 fix: update go version in makefile
  Makefile
Labels: approved, size/XS, lgtm, ok-to-test

#444 Adding Target to build darwin arm
  Makefile
Labels: approved, size/XS, lgtm, ok-to-test

#446 chore: upgrade go version to 1.17.9
  Makefile
  go.mod
  go.sum
Labels: approved, size/L

#447 chore: upgrade jx gitops version
  go.mod
  go.sum
Labels: approved, size/S

#448 fix: remove chart step as we dont release charts for jx-pipeline
  .lighthouse/jenkins-x/release.yaml
Labels: approved, size/XS

#449 fix: bump go scm to 1.11.5
  .lighthouse/jenkins-x/release.yaml
  go.mod
  go.sum
Labels: approved, size/XS

#452 chore: add debug step to fix release pipeline
  .lighthouse/jenkins-x/release.yaml
  go.mod
  go.sum
Labels: size/M, approved

#453 fix: typo with creds secrets
  .lighthouse/jenkins-x/release.yaml
Labels: size/XS

#454 fix: copy creds from tekton creds folder
  .lighthouse/jenkins-x/release.yaml
Labels: size/XS

#456 chore: upgrade gocloud dev to 0.25.0
  .lighthouse/jenkins-x/pullrequest.yaml
  go.mod
  go.sum
Labels: approved, size/XL

#457 fix: downgrade go cloud to 0.24.0
  go.mod
  go.sum
Labels: approved, size/L
