Repository jenkins-x-plugins/jx-pipeline, pull requests merged in 2022-06, with the labels that each got.

#471 chore: upgrade helper to 3.2.11
  go.mod
  go.sum
Labels: approved, size/XS

#469 fix: https clone url
  OWNERS
  OWNERS_ALIASES
  pkg/cmd/start/start.go
Labels: approved, size/S

#475 test: enable codecov
  .lighthouse/jenkins-x/pullrequest.yaml
  .lighthouse/jenkins-x/release.yaml
  Makefile
  README.md
Labels: size/M
